### PR TITLE
Allow Openvino on Mac with Intel processors

### PR DESCRIPTION
**Pull request by jamienk**
Openvino works on Mac with Intel processors

### CODE REVIEW

**Comment by jamienk** [comment]
See discussion https://github.com/rupeshs/fastsdcpu/issues/65

**Comment by rupeshs** [comment]
> Openvino works on Mac with Intel processors

Thanks, are you able to test it using Mac? ( I don't have a mac machine)

**Comment by jamienk** [comment]
It works on my 2015 Intel Mac. Thanks for all your good work

**Comment by rupeshs** [comment]
@jamienk Could you please share a screenshot?

**Comment by jamienk** [comment]
Screen Shot 2024-03-24 at 6 21 21 PM

**Pull request merged**
